
services:
  postgres:
    image: postgres
    container_name: mypostgresdb2
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - my_custom_network
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container2
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: catsarecool
    ports:
      - "5050:80"
    networks:
      - my_custom_network
      
  rabbitmq:
    image: rabbitmq:management
    container_name: myrabbitmq2
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      #- "5672:5672" # AMQP protocol
      - "15672:15672" # Management UI
    networks:
      - my_custom_network
      
  notification-service:
    build: .
    container_name: notification-system
    depends_on: 
      - postgres
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://mypostgresdb2:5432/postgres
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_RABBITMQ_ADDRESSES: amqp://myrabbitmq2
      SPRING_RABBITMQ_USERNAME: myuser
      SPRING_RABBITMQ_PASSWORD: mypass
    ports:
      - "8080:8080"
    networks:
      - my_custom_network

networks:
  my_custom_network:
    driver: bridge
      