spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
    sql:
        init:
            # initialize data.sql
            #mode: always
    rabbitmq:
        username: ${SPRING_RABBITMQ_USERNAME}
        password: ${SPRING_RABBITMQ_PASSWORD}
    mail:
        host: ${SPRING_MAIL_HOST}
        port: ${SPRING_MAIL_PORT}
        username: ${SPRING_MAIL_USERNAME}
        password: ${SPRING_MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

slack:
    bot:
        token: ${SLACK_BOT_TOKEN}