spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: mypostgresuser
        password: mypostgrespass
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
    sql:
        init:
            # initialize data.sql
            #mode: always
    rabbitmq:
        username: myrabbitmquser
        password: myrabbitmqpass
                        