spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: mypostgresuser
        password: mypostgrespass
    jpa:
        show-sql: true
    rabbitmq:
        username: myrabbitmquser
        password: myrabbitmqpass
                        